openapi: 3.0.0
info:
  title: Minha API
  description: Esta é a documentação da minha API.
  version: 1.0.0
paths:
  /users:
    get:
      summary: Lista todos os usuários
      responses:
        '200':
          description: Uma lista de usuários
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
