openapi: 3.0.0
info:
  title: Monitora Sites API
  description: https://github.com/bravo18br/api_laravel_web_scrapping
  version: 1.0.0
tags:
  - name: /api/alvo/
    description: Operações relacionadas aos Alvos
  - name: /api/wpp/
    description: Operações relacionadas ao WhatsApp
paths:
  /api/wpp/getQRCodeBIN:
    get:
      tags:
        - /api/wpp/
      summary: Obtém o QR Code em formato BIN
      responses:
        '200':
          description: Retorna QR Code em formato BIN em caso de sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  qrcode:
                    type: string
                    example: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA..."
                  status:
                    type: string
                    example: 'Sucesso'
        '500':
          description: Retorna detalhes do erro em caso de falha
          content:
            application/json:
              schema:
                type: object
                properties:
                  qrcode:
                    type: string
                    example: "Erro function geraQRCodeWPP..."
                  status:
                    type: string
                    example: 'Falha'
  /api/wpp/getQRCodePNG:
    get:
      tags:
        - /api/wpp/
      summary: Obtém o QR Code em formato PNG para download
      responses:
        '200':
          description: Inicia download do .PNG em caso de sucesso
          content:
            image/png:
              schema:
                type: Deve iniciar o download de um qrcode.png
                format: PNG
        '500':
          description: Retorna um json com mensagem de erro em caso de falha
          content:
            application/json:
              schema:
                type: string
                example: 'QRCode em PNG não gerado, falha no servidor.'

  /api/wpp/getStatusWPP:
    get:
      tags:
        - /api/wpp/
      summary: Obtém o status do WhatsApp
      responses:
        '200':
          description: Status OK do WhatsApp
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: CONNECTED
        '500':
          description: Status ERRO do WhatsApp
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Erro function statusWPP...
