openapi: 3.0.0
info:
  title: Monitora Sites API
  description: >
    API para monitoramento de sites. 
  version: 1.0.0
externalDocs:
  description: https://github.com/bravo18br/api_laravel_web_scrapping
  url: https://github.com/bravo18br/api_laravel_web_scrapping
tags:
  - name: Alvos
    description: Operações relacionadas aos Alvos
  - name: WPP Connect
    description: Operações relacionadas ao WhatsApp
  - name: Diversos
    description: Rotas diversas
paths:
  /api/wpp/getQRCodeBIN:
    get:
      tags:
        - WPP Connect
      summary: Obtém o QR Code em formato BIN
      responses:
        '200':
          description: Retorna QR Code em formato BIN em caso de sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  qrcode:
                    type: string
                    example: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA..."
                  status:
                    type: string
                    example: 'Sucesso'
        '500':
          description: Retorna detalhes do erro em caso de falha
          content:
            application/json:
              schema:
                type: object
                properties:
                  qrcode:
                    type: string
                    example: "Erro function geraQRCodeWPP..."
                  status:
                    type: string
                    example: 'Falha'
  /api/wpp/getQRCodePNG:
    get:
      tags:
        - WPP Connect
      summary: Obtém o QR Code em formato PNG para download
      responses:
        '200':
          description: Inicia download do .PNG em caso de sucesso
          content:
            image/png:
              schema:
                type: string
                format: binary
        '500':
          description: Retorna um json com mensagem de erro em caso de falha
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'QRCode em PNG não gerado, falha no servidor.'
  /api/wpp/getStatusWPP:
    get:
      tags:
        - WPP Connect
      summary: Obtém o status do WhatsApp
      responses:
        '200':
          description: Status OK do WhatsApp
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: CONNECTED
        '500':
          description: Status ERRO do WhatsApp
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Erro function statusWPP...
  /:
    get:
      tags:
        - Diversos
      summary: Abre essa página de documentação
      responses:
        '200':
          description: Documentação swagger da API
          content:
            text/html:
              schema:
                type: string
                example: '<html>...</html>'
  /api/alvo:
    get:
      tags:
        - Alvos
      summary: Lista todos os alvos
      responses:
        '200':
          description: Retorna uma lista de todos os alvos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Alvo'
    post:
      tags:
        - Alvos
      summary: Cria um novo alvo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Alvo'
      responses:
        '201':
          description: Alvo criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alvo'
        '400':
          description: Erro de validação
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Erro de validação'
  /api/alvo/atualizaConteudoAlvo:
    get:
      tags:
        - Alvos
      summary: Atualiza o conteúdo original dos alvos
      responses:
        '200':
          description: Conteúdo original atualizado com sucesso
          content:
            application/json:
              schema:
                type: string
                example: 'Conteúdo original atualizado'
        '500':
          description: Erro ao atualizar o conteúdo original
          content:
            application/json:
              schema:
                type: string
                example: 'ERRO - atualizaConteudoOriginal: ...'
  /api/alvo/{alvo}:
    get:
      tags:
        - Alvos
      summary: Obtém um alvo específico
      parameters:
        - name: alvo
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Retorna os detalhes de um alvo específico
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alvo'
        '404':
          description: Alvo não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Alvo não encontrado'
    put:
      tags:
        - Alvos
      summary: Atualiza um alvo existente
      parameters:
        - name: alvo
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Alvo'
      responses:
        '200':
          description: Alvo atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alvo'
        '400':
          description: Erro de validação
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Erro de validação'
    delete:
      tags:
        - Alvos
      summary: Deleta um alvo
      parameters:
        - name: alvo
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Alvo deletado com sucesso
        '404':
          description: Alvo não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Alvo não encontrado'
components:
  schemas:
    Alvo:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        url:
          type: string
        elemento:
          type: string
        conteudo:
          type: string
